---
# setup undercloud vm
- hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - undercloud

  vars_prompt:
    - name: "flavor"
      prompt: "Base OS Variant (centos|rhel)"
      default: "centos"

  tasks:
  - include: tasks/undercloud-provision-centos.yml
    when: flavor == "centos"
  - include: tasks/undercloud-provision-rhel.yml
    when: flavor == "rhel"

# do the initial yum update -y && reboot
- hosts: undercloud
  tags:
    - undercloud
  gather_facts: true
  tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/default.yml"
    - include: tasks/undercloud-registration-rhel.yml
      when: ansible_distribution == "RedHat"
    - name: update packages
      yum: name=* state=latest
      register: run_reboot
      tags:
        - provision

    - include: tasks/reboot-server.yml
      when: run_reboot.changed
