---
- name: upload inventory
  copy: src={{ inventory_file_source }} dest=/home/{{ undercloud_user }}/nodes.json
  tags:
    - setup
  become_user: "{{ undercloud_user }}"

- name: import inventory
  shell: |
      source ~/stackrc
      openstack baremetal import nodes.json
  tags:
    - setup
  become_user: "{{ undercloud_user }}"

- name: inventory introspection
  shell: |
      source ~/stackrc
      #openstack baremetal introspection bulk start
      openstack overcloud node introspect --all-manageable
  tags:
    - setup
  become_user: "{{ undercloud_user }}"


